Repository TXST-CS5346-AI/project-two, pull requests merged in 2021-04, with the labels that each got.

#17 Boris: updated menu and Simulation CPP implementation.
  .gitignore
  include/Simulation.hpp
  src/Simulation.cpp
  src/main.cpp
Labels: enhancement

#19 Adjustments to board - initial changes.
  include/Board.hpp
  include/Pieces.hpp
  src/Board.cpp
  src/Pieces.cpp
Labels: enhancement

#24 Feature/main menu
  include/Algorithm.hpp
  src/Algorithm.cpp
  src/main.cpp
Labels: enhancement

#26 Feature/main menu
  include/Algorithm.hpp
  include/Game.hpp
  src/Algorithm.cpp
  src/Game.cpp
  src/Simulation.cpp
Labels: enhancement

#31 Feature/main menu
  include/Algorithm.hpp
  include/Player.hpp
  src/Algorithm.cpp
  src/Game.cpp
  src/Player.cpp
Labels: enhancement

#32 put values before depth-return, added cout stepping notices in minimax
  include/Game.hpp
  src/Algorithm.cpp
Labels: enhancement

#36 Feature/main menu
  .gitignore
  src/Algorithm.cpp
  src/Simulation.cpp
  src/main.cpp
Labels: enhancement

#41 Boris: added switch to disable color output, use -nc. Added initial l…
  include/Pieces.hpp
  include/Simulation.hpp
  src/Algorithm.cpp
  src/Board.cpp
  src/Pieces.cpp
  src/Simulation.cpp
  src/main.cpp
Labels: bug, enhancement

#45 Too much to count
  include/Algorithm.hpp
  include/Game.hpp
  include/Pieces.hpp
  include/Player.hpp
  include/Simulation.hpp
  src/Algorithm.cpp
  src/Game.cpp
  src/Pieces.cpp
  src/Player.cpp
  src/Simulation.cpp
  src/main.cpp
Labels: bug, enhancement

#47 Feature/boris eval and comments
  include/Algorithm.hpp
  include/Board.hpp
  include/Game.hpp
  include/Pieces.hpp
  include/Player.hpp
  include/Simulation.hpp
  src/Algorithm.cpp
  src/Board.cpp
  src/Game.cpp
  src/Pieces.cpp
  src/Player.cpp
  src/Simulation.cpp
  src/main.cpp
Labels: bug, enhancement

#52 Feature/boris eval and comments
  Project2.cpp
  src/Simulation.cpp
Labels: bug
